package my.krbmod.automc.utility;
//
// Class to manage time as string "MM:SS" and convert to and from seconds in Integer format.
//
public class TimeString {

	String timeString;

	public TimeString() {
		timeString = "00:00";
	}
	
	public TimeString(String s) {
		//
		// Rather than check if string is valid, use static helper functions to force it to an integer and back
		// Static helper functions will perform the validity checks
		//
		timeString = TimeString.toTimeString(TimeString.toSeconds(s));
	}
	
	public TimeString(int t) {
		//
		// We ignore the sign if parameter is negative
		// 		//
		timeString = TimeString.toTimeString(Math.abs(t));
	}
	
	public String toString() {
		return timeString;
	}
	
	public int toSeconds(){
		return toSeconds(timeString);
	}
	
	public static int toSeconds(String timeString){
		
		// TODO - Validate input parameter
		String[] units = timeString.split(":");
		// TODO - Confirm split was successful
		
		int minutes = Integer.parseInt(units[0]);
		// TODO - Catch exceptions generated by parseInt for invalid Ints
		int seconds = Integer.parseInt(units[1]);
		// TODO - Catch exceptions generated by parseInt for invalid Ints
		
		return 60 * minutes + seconds;
	}
	
	public static String toTimeString(int s){
		String result = "";

		// We ignore the sign if parameter is negative
		int minutes = Math.abs(s / 60);
	    int seconds = (Math.abs(s) - (minutes * 60));
	     
	    return String.format("%02d:%02d", minutes, seconds);
				
	}
}
